language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.0.26'
  - '7.0.27'
  - '7.1.0'
  - '7.1.1'
  - '7.1.2'
  - '7.1.3'
  - '7.1.4'
  - '7.1.5'
  - '7.1.6'
  - '7.1.7'
  - '7.1.8'
  - '7.1.9'
  - '7.1.10'
  - '7.1.11'
  - '7.1.12'
  - '7.1.13'
  - '7.1.14'
  - '7.1.15'
  - '7.1.16'
  - '7.1.17'
  - '7.1.18'
  - '7.1.19'
  - '7.1.20'
  - '7.1.21'
  - '7.2.0'
  - '7.2.1'
  - '7.2.2'
  - '7.2.3'
  - '7.2.4'
  - '7.2.5'
  - '7.2.6'
  - '7.2.7'
  - '7.2.8'
  - '7.2.9'
  - nightly
os:
  - linux
  - windows

install: composer install

script: phpunit --verbose --debug
